#' preprocess Z
#'
#' if requested, fixed effect dummies will be incorporated
#'
#' @param Z matrix of predictors(Nxd)
#' @param fixed_effects a vector of fixed-effect identifiers, as generated by \code{\link{make_fixedeffects}()}
#' @noRd
preprocess_Z <- function(Z, fixed_effects)
{
  ## if requested, incorporate matrix of fixed effects
  if(!is.null(fixed_effects))
  {
    femat <- make_FE_mat(fixedeffects = fixed_effects)
    Z <- cbind(femat, Z)
  }

  return(Z)
}
